### PR TITLE
Release/generator/0.10.0

### PR DESCRIPTION
**Pull request by Tyrrx**

### CODE REVIEW

**Comment by WiiPlayer2** [comment]
The commit on this branch should also go in develop before merging into master

**Comment by Tyrrx** [comment]
@WiiPlayer2 Well, the branch comes from the latest develop..

**Comment by Tyrrx** [comment]
Nvm the target has changed

**Comment by Tyrrx** [comment]
@WiiPlayer2 Done in https://github.com/RESTyard/RESTyard/pull/71

**Review by WiiPlayer2 — APPROVED** [review]
Should be ok now (without squash)

**Pull request merged**
